### ISSUE TITLE
토글 기능

### ISSUE THREAD

**Issue by hyeincha** [zzw-final/zzw-FE_DEL#7]
## Issue: ✅ FEATURE
레시피 카드, 팔로우/팔로워 토글 기능

## Description
마이페이지의 '내가 쓴 글'과 '내가 좋아요 한 글'
팔로우페이지의 '팔로우'와 '팔로워'

각각 내가 쓴 글 리스트, 팔로우 리스트를 기본값으로 두고 
내가 좋아요 한 글, 팔로워를 클릭하면 다른 리스트 렌더링 필요

## Todo
- [x] 버튼 Focus 상태일 때와 아닐 때 각각 다른 디자인 주기
- [x] Focus 상태인 버튼의 상태를 가져와서 각각 다른 정보 렌더링

## ETC
부드럽게 전환되는 애니메이션도 넣을 수 있으면 좋을 것 같음
팔로워 페이지 닉네임 검색 기능

**Comment by suzz-in** [comment]
디자인까지 신경을..! 좋습니다 화이팅해봅시다😀
